config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"

  resources :tweets
  resources :users
  resources :likes, only: %i[create]
  
  #customs routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get "/profile", to: "users#edit"
  patch "/profile", to: "users#update"
  post "/profile", to: "users#create"

   # Omniauth
   get "/auth/github/callback", to: "sessions#create"

  #routes to API tests
  namespace :api do
    resources :tweets, except: %i[new edit]
    resources :users, except: %i[new edit]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :likes, dependent: :destroy, inverse_of: "tweet"
  has_many :tweets, class_name: "Tweet", 
                                    foreign_key: "replied_to_id",
                                    dependent: :nullify,
                                    inverse_of: "replied_to"
  belongs_to :replied_to, class_name: "Tweet", optional: true, counter_cache: :replies_count

  # Validates
  validates :body, presence: true, length: { maximum: 140 }
  validates :image, presence: false
end

app/controllers/api/tweets_controller.rb
module Api
  class TweetsController < ApiController
    def index
      @tweets = Tweet.all
      render json: @tweets, status: :ok
    end
  
    # GET apì/tweets/:id
    def show
      @tweet = Tweet.all
      render json: @tweet, status: :ok
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  after_action :verify_policy_scoped, only: %i[ index ]
  after_action :verify_authorized, only: %i[ update ]

  # GET /tweets
  def index
    @tweet_new = Tweet.new
    @like_new = Like.new
    @tweets = Tweet.all
  
    # Select those tweets belonging to current_user (only if it's logged in). Used to filter those who can be edited or deleted. 
    # Select all for admins 
    # @user_tweets = current_user ? current_user.tweets : [] 
    # @user_tweets = current_user ? policy_scope( Tweet ) : []
    @user_tweets = policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /tweets/1
  def show
    #  @tweet -> Default
    @tweet_new = Tweet.new
    @like_new = Like.new
    @user_tweets =  policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    # binding.pry
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      if params[:tweet][:replied_to_id].empty? # Si no hay un replied hablamos de un tweet
        redirect_to tweets_path, notice: "Tweet was successfully created."
      else
        redirect_to @tweet.replied_to, notice: "Retweet was successfully created"
      end
    else
      if params[:tweet][:replied_to_id].empty? # Si no hay un replied hablamos de un tweet
        redirect_to tweets_path, notice: "Cannot tweet"
      else
        redirect_to @tweet.replied_to, notice: "Cannot retweet"
      end
    end
  end

  # PATCH/PUT /tweets/1
  def update
    # @tweet by default
    authorize @tweet
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: "Tweet was successfully updated."
    else
      redirect_to @tweet, notice: "Tweet cannot be updated."
      # render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @parent_tweet = @tweet.replied_to
    @tweet.destroy
    if @parent_tweet.nil?
      redirect_to tweets_url, notice: "Tweet was successfully destroyed."
    else
      redirect_to @parent_tweet, notice: "Retweet was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :replied_to_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_comment.html.erb
<div>
    <%= form_with url: tweets_path, model: tweet_new do |form| %>
        <div class="tweet-new">
            <%= form.text_area :body, placeholder: "Remember to thing before write...", rows: 3, class: "tweet-body"%>
            <% if !parent_tweet.nil? %>
                <%= form.hidden_field :replied_to_id, value: parent_tweet.id %>
            <% else %>
                <%= form.hidden_field :replied_to_id, value: nil %>
            <% end %>

            <%= form.submit "Tweet", class: "button button--primary overline"%>
        </div>   
    <% end %>
<div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <div class="tweet-new">
    <% if tweet.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <%= form.text_area :body, placeholder: "Remember to thing before write...", rows: 3, class: "tweet-body w-full"%>
      <%= form.submit "Update", class: "button button--primary overline"%>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweet-card">
  <div class="tweet-card__header"> <!-- Header -->
    <div class="user-avatar">
      <% if tweet.user.avatar.attached? %>
        <%= image_tag tweet.user.avatar %>
      <% else %>
        <%=  image_tag "user/default_user.jpg"%>
      <% end %>
    </div>
    <%= link_to tweet.user, class: "text-decoration-none gray-900" do%>
      <div class="mx-0.25">
        <div class="flex gap-0.25">
          <h2 class="font-primary bold text-md"><%= tweet.user.name%></h2>
          <h2 class="font-primary regular text-md pink-600">@<%= tweet.user.username%></h2>
        </div>
         <p class="font-primary regular text-sm gray-500"><%= time_ago_in_words(tweet.created_at)%> ago</p>
      </div>
    <% end %>
  </div>
  <%= link_to tweet, class: "text-decoration-none gray-900" do %>
    <div class="tweet-card__body"> <!-- Body -->
        <p class="font-primary regular text-md"><%= tweet.body %></p>
    </div>
  <% end %>
  <div class="tweet-card__footer"> <!--Footer -->
    
    <div class="tweet-card__footer-buttons1"> <!-- First two buttons -->
      <% if user_tweets.include?(tweet) %>
        <%= button_to tweet, method: :delete, class: "button-cleaned" do %>
          <%= image_tag "icons/erase.png" %>
        <% end %>
        <%= button_to  edit_tweet_path(tweet), method: :get, class: "button-cleaned" do %>
          <%= image_tag "icons/edit.png" %>
        <% end %>
      <% end %>
    </div>

    <div class="tweet-card__footer-buttons2"> <!-- Last two buttons -->
      
      <%= link_to tweet do %>
        <%= image_tag "icons/retweet.png" %>
      <% end %>
      <p><%= tweet.replies_count %></p>

      <%= form_with url: likes_path, model: like_new do |form| %>
        <%= form.hidden_field :tweet_id, value: tweet.id %>
        
        <%if user_likes.include?(tweet) %>
          <%= image_submit_tag "icons/liked.png" %>
        <% else %>
          <%= image_submit_tag "icons/like.png" %>
        <% end %>
      <% end %>
      <p><%= tweet.likes_count %></p>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1 class="semibold head-sm">Editing tweet</h1>
    </div>
    
    <div>
      <%= render "form", tweet: @tweet %>
    </div>

    <br>

    <div>
      <%= link_to "Show this tweet", @tweet %> |
      <%= link_to "Back to tweets", tweets_path %>
    </div>

  </div>
</section>

app/views/tweets/index.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <div class="w-full center mb-1">
      <h1 class="semibold head-sm">Home</h1>
    </div>

    <% if  current_user %>
      <div>
        <%= render "comment", tweet_new: @tweet_new, parent_tweet: nil %>
      </div>
    <% end %>

    <div>
      <% @tweets.sort.reverse.each do |tweet| %>
        <% if tweet.replied_to.nil? %>
          <%= render tweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
        <% end %>
      <% end %>
    </div>

    <%= link_to "New tweet", new_tweet_path %>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <%= render @tweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>

    <hr class="for-retweets">

    <% if current_user %>
      <div>
        <%= render "comment", tweet_new: @tweet_new, parent_tweet: @tweet %>
      </div>
    <% end %>

    <div>
      <% @tweet.tweets.each do |retweet| %>
        <%= render retweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
      <% end %>
    </div>
  </div>
</section>