config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"

  resources :tweets
  resources :users
  resources :likes, only: %i[create]
  
  #customs routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get "/profile", to: "users#edit"
  patch "/profile", to: "users#update"
  post "/profile", to: "users#create"

   # Omniauth
   get "/auth/github/callback", to: "sessions#create"

  #routes to API tests
  namespace :api do
    resources :tweets, except: %i[new edit]
    resources :users, except: %i[new edit]
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar

    has_many :tweets, dependent: :nullify
    has_many :likes, dependent: :destroy, inverse_of: "user"
    has_many :liked_tweets, through: :likes, source: :tweet
    enum role: { admin: 0, user: 1 } 
    #bcrypt
    has_secure_password

    # Validations
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}, allow_blank: false
    validates :username, presence: true, uniqueness: true
    validates :avatar, presence: false
    validates :password_digest, presence: true, uniqueness: true
end

app/controllers/api/users_controller.rb
module Api
    class UsersController < ApiController
       # GET api/users
      def index
        @users = User.all
        render json: @users, status: :ok
      end
    
      # GET apì/users/:id
      def show
        @user = User.find(params[:id])
        render json: @user, status: :ok
      end

      # POST api/users
      def create
        @user = User.new(user_params)
    
        if @user.save
          render json: @user, status: :created
        else
            render json: @user.errors , status: :unprocessable_entity
        end
      end

      # DELETE api/users/1
      def destroy
          @user = User.find(params[:id])
          @user.destroy
          render json: {}, status: :no_content
      end


      private
        def user_params
        params.require(:user).permit(:email, :username, :name, :password, :password_confirmation)
        end
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create edit]
  after_action :verify_authorized, only: %i[update]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @like_new = Like.new
    @user = User.find(params[:id])
    @user_tweets = policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /profile
  def edit
    if params.has_key?(:id)
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :username, :name, :password, :password_confirmation, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, url: "/profile") do |form| %>
  <div class="user--form">
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="center">
      <p class="mb-1 text-xs overline">Continue with</p>
      <div data-turbo="false" class="mb-1">
        <%=form_with(url: "/auth/github", method: :post) do |f|%>
          <%=f.submit "Login with github", class: "w-full button button--secondary mb-1"%>
        <%end%>
      </div>
      <p class="mb-1 text-xs overline">Or</p>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :username, class: "text-xs overline block"%>
        <%= form.text_field :username, class: "input", placeholder: "example" %>
      </div>  
      <% if user.errors.messages[:username].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:username].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
          <%= form.label :email, class:"text-xs overline block"%>
          <%= form.email_field :email, class: "input", placeholder: "example@gamil.com" %>
      </div>
      <% if user.errors.messages[:email].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:email].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :name, class:"text-xs overline block"%>
        <%= form.text_field :name, class: "input", placeholder: "Example Name" %>
      </div>
      <% if user.errors.messages[:name].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:name].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div class="user-main-image">
        <%= image_tag "user/default_user.jpg" %>
      </div>
      <div>
        <%= form.label :avatar, class:"text-xs overline block"%>
        <%= form.file_field :avatar, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:avatar].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:avatar].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password, class:"text-xs overline block"%>
        <%= form.password_field :password, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password_confirmation, class:"text-xs overline block"%>
        <%= form.password_field :password_confirmation, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password_confirmation].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password_confirmation].join(", ")%>
        </span>
      <% end %>
    </div>


    <div class="center">
      <%= form.submit "SIGN UP", class: "w-full button button--primary mb-1" %>
      
      <p class="mb-1">Already a member?</p>
      <%= link_to "Sign in", login_path, class: "text-decoration-none pink-600"%>
    </div>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_with(model: user) do |form| %>
  <div class="user--form">
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-1">
        <div>
          <%= form.label :username, class:"text-xs overline block"%>
          <%= form.text_field :username, class: "input", placeholder: "example" %>
        </div>
        <% if user.errors.messages[:username].any? %>
          <span class="content-sm input__error-message block">
            <%= user.errors.messages[:username].join(", ")%>
          </span>
        <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :email, class:"text-xs overline block"%>
        <%= form.email_field :email, class: "input", placeholder: "example@gamil.com" %>
      </div>
      <% if user.errors.messages[:email].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:email].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :name, class:"text-xs overline"%>
        <%= form.text_field :name, class: "input", placeholder: "Example Name" %>
      </div>
      <% if user.errors.messages[:name].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:name].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div class="user-main-image">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar %>
          <% else %>
            <%= image_tag "user/default_user.jpg"%>
          <% end %>
      </div>
      <div>
        <%= form.label :avatar, class:"text-xs overline"%>
        <%= form.file_field :avatar, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:avatar].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:avatar].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password, class:"text-xs overline"%>
        <%= form.password_field :password, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password_confirmation, class: "text-xs overline"%>
        <%= form.password_field :password_confirmation, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password_confirmation].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password_confirmation].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :current_password, class:"text-xs overline"%>
        <%= form.password_field :password_confirmation, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password_confirmation].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password_confirmation].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="w-full">
      <%= form.submit "UPDATE", class: "w-full button button--primary" %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div>
  <div class="w-full center mb-1">
    <h1 class="semibold head-sm">Profile<h1>
  </div>

  <div class="user-main-image">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar%>
    <% else %>
      <%= image_tag "user/default_user.jpg"%>
    <% end %>
  </div>
  <div class="w-full center mb-1.5">
    <h2 class="semibold head-xs mb-0.25"><%= user.name %></h2>
    <p class="font-primary regular text-md gray-500 mb-0.25"><%= user.username %><p>
    <p class="font-primary regular text-md gray-500 mb-1"><%= user.created_at.strftime("Joined on %B %d, %Y") %></p>
    <% if current_user and (current_user.admin? or  current_user == user) %>
      <div class="flex justify-center">
        <%= link_to "Edit Profile", edit_user_path(user), class: "button user-button-create button--primary"%>
      </div>
    <% end %>
  </div>

  <input type="radio" id="c-tweets" name="selection" checked/>
  <input type="radio" id="c-liked-tweets" name="selection"/>

  <div class="tabs">
    <div class="tabs-element-tweets">
      <label for="c-tweets" id="toggle-tweets">
        <h3 class="font-primary regular text-md">Tweets (<%= user.tweets.length%>)</h3>
      </label>
    </div>
    <div class="tabs-element-liked-tweets">
      <label for="c-liked-tweets" id="toggle-liked-tweets">
        <h3 class="font-primary regular text-md">Likes (<%= user.liked_tweets.length%>)</h3>
      </label>
    </div>
  </div>
  <!-- User tweets -->
  <div class="expandable-tweets">
    <% user.tweets.each do |tweet| %>
      <%= render "/tweets/tweet", tweet: tweet, like_new: like_new, user_tweets: user_tweets, user_likes: user_likes %>
      <% end %>
  </div>
  <!-- User liked tweets -->
  <div class="expandable-liked-tweets">
    <% user.liked_tweets.each do |tweet|%>
      <%= render "/tweets/tweet", tweet: tweet, like_new: like_new, user_tweets: user_tweets, user_likes: user_likes %>
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1>Edit Profile</h1>
    </div>
  </div>

  <% if current_user %>
    <div class="container-sm">
      <%= render "form_edit", user: @user %>
    </div>
  <% end %>
</section>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1>Create an account</h1>
    </div>
  </div>

  <div class="container-sm">
    <%= render "form", user: @user %>
  </div>
</section>

app/views/users/show.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <%= render @user, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
  </div>
</section>