config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"

  resources :tweets
  resources :users
  resources :likes, only: %i[create]
  
  #customs routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get "/profile", to: "users#edit"
  patch "/profile", to: "users#update"
  post "/profile", to: "users#create"

   # Omniauth
   get "/auth/github/callback", to: "sessions#create"

  #routes to API tests
  namespace :api do
    resources :tweets, except: %i[new edit]
    resources :users, except: %i[new edit]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>© 2021 - Codeable Critics</p>
    <p>Build with ❤ by</p>
    <div class="footer-content">
        <div class="footer-content__student">
            <%= image_tag "icons/linkedin.png"%>
            <p>Luis Zelada</p>
        </div>
        <div class="footer-content__student">
            <%= image_tag "icons/linkedin.png"%>
            <p>The Crazy Dave</p>
        </div>
        <div class="footer-content__student">
            <%= image_tag "icons/linkedin.png"%>
            <p>Student Name</p>
        </div>
        <div class="footer-content__student">
            <%= image_tag "icons/linkedin.png"%>
            <p>Student Name</p>
        </div>
        <div class="footer-content__student">
            <%= image_tag "icons/linkedin.png"%>
            <p>Student Name</p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
    <header class="header">
      <!-- bg gray -->
      <div class="container-lg">
        <nav class="navbar">
          <input type="checkbox" id="menu-mobile" />

          <a href="/#" class="text-decoration-none header--menu-mobile">
            <%= image_tag "icons/logo.png" %>
          </a>

            <!-- option 1 -->
            <label for="menu-mobile" id="toggle-close">
              <i class="ri-close-fill ri-xl"></i>
            </label>

            <!-- option 2 -->
            <label for="menu-mobile" id="toggle-open">
              <i class="ri-menu-line ri-xl"></i>
            </label>

            
          <ul class="expandable navbar--links list-style-none">
            <% if logged_in? %>
                <li>
                   <%= link_to "Edit profile","/profile", class: "link text-sm"%>
                </li>
                <li>
                    <%= link_to "Logout", sessions_path, class: "text-decoration-none button button--xs button--secondary", data: {turbo_method: :delete } %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Login", sessions_path,  class: "button text-decoration-none button--primary", data: {turbo_method: :post } %>
                </li>
            <% end %>
          </ul>

        </nav>
      </div>   
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">
     <%= render "layouts/header"%>
     <div class="body-content"><!-- body-->
      <p> <%= flash[:message]%> </p>
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>